# Generated by Django 5.2.7 on 2025-10-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='id',
        ),
        migrations.AddField(
            model_name='fixture',
            name='api_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
