# Generated by Django 5.2.7 on 2025-10-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdataapp', '0002_remove_fixture_id_fixture_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestats',
            name='away_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixture_stats', to='sportsdataapp.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixturestats',
            name='home_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixture_stats', to='sportsdataapp.team'),
            preserve_default=False,
        ),
    ]
