# Generated by Django 5.2.7 on 2025-10-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdataapp', '0003_fixturestats_away_team_fixturestats_home_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='logo_url',
            new_name='logo',
        ),
    ]
