# Generated by Django 5.2.7 on 2025-10-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdataapp', '0006_alter_fixture_away_team_alter_fixture_home_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='national',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
