# Generated by Django 5.2.7 on 2025-10-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsdataapp', '0007_alter_team_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasoncompetition',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsdataapp.venue'),
        ),
    ]
